
-   name: Brave APT Key
    become: yes
    apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        state: present

-   name: Brave Repo
    become: yes
    apt_repository:
        repo: "deb https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present

-   name: Install Brave
    become: yes
    apt:
        name: brave-browser
        state: present
        update_cache: yes
