-   include_tasks: packages.yml
-   include_tasks: git.yml
-   include_tasks: bash.yml
-   include_tasks: aqua.yml
#-   include_tasks: wayland.yml
-   include_tasks: brave.yml
-   include_tasks: docker.yml
-   include_tasks: virtual_box.yml
-   include_tasks: vscode.yml
